# Generated by Django 5.0.6 on 2024-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
