# Generated by Django 5.0.6 on 2024-05-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_my'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my',
        ),
    ]
