# Generated by Django 5.0.6 on 2024-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
